### ISSUE TITLE
我安装的 wphp82 但是默认支持的扩展ffi.so不存在

### ISSUE THREAD

**Issue by maojindao55** [wlnmp/wlnmp#11]
我看文档说php8.2默认支持ffi但是开启后报错，`PHP Warning:  PHP Startup: Unable to load dynamic library 'ffi' (tried: /usr/local/php/lib/php/extensions/no-debug-non-zts-20220829/ffi (/usr/local/php/lib/php/extensions/no-debug-non-zts-20220829/ffi: cannot open shared object file: No such file or directory), /usr/local/php/lib/php/extensions/no-debug-non-zts-20220829/ffi.so (/usr/local/php/lib/php/extensions/no-debug-non-zts-20220829/ffi.so: cannot open shared object file: No such file or directory)) in Unknown on line 0`

尝试安装也提示不存在 

```
sudo yum install wphp82-ffi

Repository epel is listed more than once in the configuration
上次元数据过期检查：2:57:41 前，执行于 2024年06月25日 星期二 08时46分25秒。
No match for argument: wphp82-ffi
错误：没有任何匹配: wphp82-ffi

```

**Comment by whsir** [comment]
默认表示默认已经存在了，不需要额外安装这个模块，可以php -m | grep FFI
