### ISSUE TITLE
提示证书过期

### ISSUE THREAD

**Issue by jackfish0405** [wlnmp/wlnmp#2]
哈喽 这个证书过期怎么破？
curl -fsSL "https://sh.wlnmp.com/wlnmp.sh" | bash
curl: (60) Peer's Certificate has expired.
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

**Comment by whsir** [comment]
请提供下当前系统及版本号，ping sh.wlnmp.com的返回结果。
请确认是偶发性还是必然性。

**Comment by whsir** [comment]
忽略该证书问题可使用以下方式
`curl -fsSLk "https://sh.wlnmp.com/wlnmp.sh" | bash`

**Comment by whsir** [comment]
目前我这边无法复现，也可关注”吴昊博客“公众号后加群反馈

**Comment by whsir** [comment]
确认当前服务器时间是否正常，服务器时间异常也有可能导致该问题出现
