### ISSUE TITLE
希望加强下可用性

### ISSUE THREAD

**Issue by hanfeicode** [wlnmp/wlnmp#4]
![image](https://github.com/wlnmp/wlnmp/assets/10413864/4971a459-ac0b-4274-8979-1d8b363f8f9b)

大概好几个月了 😒

**Comment by hanfeicode** [comment]
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to down.whsir.com:443

**Comment by whsir** [comment]
加群远程看下，我这边看都是正常的
